CREATE TABLE [Client].[Databases] (
    [guid]                                UNIQUEIDENTIFIER NOT NULL,
    [name]                                [sysname]        NOT NULL,
    [database_id]                         INT              NOT NULL,
    [source_database_id]                  UNIQUEIDENTIFIER NULL,
    [owner_sid]                           VARBINARY (MAX)  NOT NULL,
    [create_date]                         DATETIME         NOT NULL,
    [compatibility_level]                 INT              NOT NULL,
    [collation_name]                      [sysname]        NOT NULL,
    [user_access]                         BIT              NOT NULL,
    [user_access_desc]                    NVARCHAR (260)   NOT NULL,
    [is_read_only]                        BIT              NOT NULL,
    [is_auto_close_on]                    BIT              NOT NULL,
    [is_auto_shrink_on]                   BIT              NOT NULL,
    [state]                               INT              NOT NULL,
    [state_desc]                          NVARCHAR (260)   NOT NULL,
    [is_in_standby]                       BIT              NOT NULL,
    [is_cleanly_shutdown]                 BIT              NOT NULL,
    [is_supplemental_logging_enabled]     BIT              NOT NULL,
    [snapshot_isolation_state]            INT              NOT NULL,
    [snapshot_isolation_state_desc]       NVARCHAR (260)   NOT NULL,
    [is_read_committed_snapshot_on]       BIT              NOT NULL,
    [recovery_model]                      INT              NOT NULL,
    [recovery_model_desc]                 NVARCHAR (260)   NOT NULL,
    [page_verify_option]                  INT              NOT NULL,
    [page_verify_option_desc]             NVARCHAR (260)   NOT NULL,
    [is_auto_create_stats_on]             BIT              NOT NULL,
    [is_auto_create_stats_incremental_on] BIT              NOT NULL,
    [is_auto_update_stats_on]             BIT              NOT NULL,
    [is_auto_update_stats_async_on]       BIT              NOT NULL,
    [is_ansi_null_default_on]             BIT              NOT NULL,
    [is_ansi_nulls_on]                    BIT              NOT NULL,
    [is_ansi_padding_on]                  BIT              NOT NULL,
    [is_ansi_warnings_on]                 BIT              NOT NULL,
    [is_arithabort_on]                    BIT              NOT NULL,
    [is_concat_null_yields_null_on]       BIT              NOT NULL,
    [is_numeric_roundabort_on]            BIT              NOT NULL,
    [is_quoted_identifier_on]             BIT              NOT NULL,
    [is_recursive_triggers_on]            BIT              NOT NULL,
    [is_cursor_close_on_commit_on]        BIT              NOT NULL,
    [is_local_cursor_default]             BIT              NOT NULL,
    [is_fulltext_enabled]                 BIT              NOT NULL,
    [is_trustworthy_on]                   BIT              NOT NULL,
    [is_db_chaining_on]                   BIT              NOT NULL,
    [is_parameterization_forced]          BIT              NOT NULL,
    [is_published]                        BIT              NOT NULL,
    [is_subscribed]                       BIT              NOT NULL,
    [is_merge_published]                  BIT              NOT NULL,
    [is_distributor]                      BIT              NOT NULL,
    [is_broker_enabled]                   BIT              NOT NULL,
    [log_reuse_wait]                      INT              NOT NULL,
    [log_reuse_wait_desc]                 NVARCHAR (260)   NOT NULL,
    [is_cdc_enabled]                      BIT              NOT NULL,
    [VLFCount]                            INT              NOT NULL,
    [NumberOfDataFiles]                   INT              NOT NULL,
    [NumberOfLogFiles]                    INT              NOT NULL,
    [IsBizTalk]                           BIT              CONSTRAINT [DF_Databases_IsBizTalk] DEFAULT ((0)) NOT NULL,
    [IsCRMDynamics]                       BIT              CONSTRAINT [DF_Databases_IsCRMDynamics] DEFAULT ((0)) NOT NULL,
    [IsSharePoint]                        BIT              CONSTRAINT [DF_Databases_IsSharePoint] DEFAULT ((0)) NOT NULL,
    [IsSAP]                               BIT              CONSTRAINT [DF_Databases_IsSAP] DEFAULT ((0)) NOT NULL,
    [IsTFS]                               BIT              CONSTRAINT [DF_Databases_IsTFS] DEFAULT ((0)) NOT NULL
) TEXTIMAGE_ON [Client];




GO
CREATE CLUSTERED INDEX [CIX_guid]
    ON [Client].[Databases]([guid] ASC) WITH (FILLFACTOR = 90)
    ON [Client];

